services:
  postgres:
    image: postgres:16-alpine
    container_name: nash-postgres
    environment:
      POSTGRES_DB: nashdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d nashdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: nash-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: nash-api
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:qwerty@postgres:5432/nashdb
      REDIS_URL: redis://redis:6379/0
      HOST: 0.0.0.0
    ports:
      - "8000:8000"
    profiles: ["full"]

volumes:
  postgres_data:
