"""Declarative base and the columns every table carries.

Every model inherits :class:`BaseModel`, so `id`, `created_at`, and `updated_at` are guaranteed
across the schema. The naming convention is set on the metadata so Alembic emits stable, explicit
constraint names — without it, autogenerated downgrades cannot drop unnamed constraints.
"""

from __future__ import annotations

import enum
import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, MetaData, Uuid, func
from sqlalchemy import Enum as SqlEnum
from sqlalchemy.orm import DeclarativeBase, Mapped, declared_attr, mapped_column

NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class BaseModel(Base):
    """UUID primary key plus creation and update timestamps."""

    __abstract__ = True

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    def __repr__(self) -> str:
        return f"<{type(self).__name__} id={self.id}>"


class TenantScopedModel(BaseModel):
    """Every table owned by a tenant inherits this.

    Declaring ``tenant_id`` once — rather than on each model — is what lets
    :class:`~src.shared.database.repository.TenantScopedRepository` guarantee at the type level that
    a scoped query is possible. Tenant isolation is the project's worst failure mode (spec §5.7), so
    it is structural, not a convention each module has to remember.
    """

    __abstract__ = True

    @declared_attr
    @classmethod
    def tenant_id(cls) -> Mapped[uuid.UUID]:
        return mapped_column(
            Uuid(as_uuid=True),
            ForeignKey("tenant.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        )


def enum_column(enum_type: type[enum.Enum], name: str, length: int = 32) -> SqlEnum:
    """A varchar-backed enum that stores the member's **value**, not its name.

    SQLAlchemy's default is to persist ``.name`` (``"DRAFT"``), while every ``server_default`` in
    the migrations — and every JSON response — uses ``.value`` (``"draft"``). The two only ever
    agreed because the ORM always supplies the column; a row inserted without it would store the
    default and then fail to load. ``values_callable`` makes the stored form the value everywhere,
    so the database, the defaults, and the API all read the same.
    """
    return SqlEnum(
        enum_type,
        name=name,
        native_enum=False,
        length=length,
        values_callable=lambda members: [member.value for member in members],
    )
