# Generated by `python -m src.configs.generate` — do not edit by hand.
from typing import Any

__all__: list[str]

class ConfigError(RuntimeError): ...

def load_config() -> dict[str, Any]: ...
def reload() -> None: ...

APP_DEBUG: bool
APP_ENV: str
APP_NAME: str
APP_VERSION: str
CORS_ALLOW_ORIGINS: list[str]
DATABASE_ECHO: bool
DATABASE_MAX_OVERFLOW: int
DATABASE_POOL_SIZE: int
DATABASE_URL: str
DOCS_ENABLED: bool
DOCS_OPENAPI_PATH: str
DOCS_REDOC_PATH: str
DOCS_SWAGGER_PATH: str
LOGGING_LEVEL: str
REDIS_URL: str
SERVER_HOST: str
SERVER_PORT: int
