"""Regenerates ``src/configs/__init__.pyi`` from ``application.yaml``.

Run after adding, removing, or retyping a configuration key::

    python -m src.configs.generate

The stub is what gives ``from src.configs import DATABASE_URL`` a real type under mypy.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from src.configs.loader import load_config

STUB_FILE = Path(__file__).parent / "__init__.pyi"

_HEADER = """# Generated by `python -m src.configs.generate` — do not edit by hand.
from typing import Any

__all__: list[str]

class ConfigError(RuntimeError): ...

def load_config() -> dict[str, Any]: ...
def reload() -> None: ...

"""


def _annotation(value: Any) -> str:
    if isinstance(value, bool):
        return "bool"
    if isinstance(value, int):
        return "int"
    if isinstance(value, float):
        return "float"
    if isinstance(value, list):
        return "list[str]"
    return "str"


def render() -> str:
    config = load_config()
    lines = [f"{key}: {_annotation(value)}" for key, value in sorted(config.items())]
    return _HEADER + "\n".join(lines) + "\n"


def main() -> None:
    STUB_FILE.write_text(render(), encoding="utf-8")
    print(f"wrote {STUB_FILE}")


if __name__ == "__main__":
    main()
