"""agents

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-28 16:17:03.282488
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("persona", sa.Text(), nullable=False),
        sa.Column(
            "engagement_rules",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "guardrails",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "model_provider",
            sa.Enum(
                "GEMINI", "OPENAI", "ANTHROPIC", name="model_provider", native_enum=False, length=32
            ),
            nullable=True,
        ),
        sa.Column(
            "model_config_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT", "PUBLISHED", "PAUSED", name="agent_status", native_enum=False, length=32
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenant.id"], name=op.f("fk_agent_tenant_id_tenant"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent")),
    )
    op.create_index(op.f("ix_agent_status"), "agent", ["status"], unique=False)
    op.create_index(op.f("ix_agent_tenant_id"), "agent", ["tenant_id"], unique=False)
    op.create_table(
        "agent_version",
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("note", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agent.id"],
            name=op.f("fk_agent_version_agent_id_agent"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_version")),
        sa.UniqueConstraint("agent_id", "version", name="uq_agent_version_agent_id_version"),
    )
    op.create_index(op.f("ix_agent_version_agent_id"), "agent_version", ["agent_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_agent_version_agent_id"), table_name="agent_version")
    op.drop_table("agent_version")
    op.drop_index(op.f("ix_agent_tenant_id"), table_name="agent")
    op.drop_index(op.f("ix_agent_status"), table_name="agent")
    op.drop_table("agent")
    # ### end Alembic commands ###
