"""knowledge base

Revision ID: 0004
Revises: 0003
Create Date: 2026-08-28 21:03:57.672028
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "knowledge_base",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "retrieval_tier",
            sa.Enum("DIRECT", "KEYWORD", name="retrieval_tier", native_enum=False, length=32),
            server_default="direct",
            nullable=False,
        ),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_knowledge_base_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_base")),
        sa.UniqueConstraint("tenant_id", "name", name="uq_knowledge_base_tenant_id_name"),
    )
    op.create_index(
        op.f("ix_knowledge_base_tenant_id"), "knowledge_base", ["tenant_id"], unique=False
    )
    op.create_table(
        "agent_kb_link",
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("kb_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agent.id"],
            name=op.f("fk_agent_kb_link_agent_id_agent"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["kb_id"],
            ["knowledge_base.id"],
            name=op.f("fk_agent_kb_link_kb_id_knowledge_base"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_kb_link")),
        sa.UniqueConstraint("agent_id", "kb_id", name="uq_agent_kb_link_agent_id_kb_id"),
    )
    op.create_index(op.f("ix_agent_kb_link_agent_id"), "agent_kb_link", ["agent_id"], unique=False)
    op.create_index(op.f("ix_agent_kb_link_kb_id"), "agent_kb_link", ["kb_id"], unique=False)
    op.create_table(
        "kb_source",
        sa.Column("kb_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column(
            "type",
            sa.Enum("FILE", "URL", "MANUAL", name="kb_source_type", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "READY",
                "FAILED",
                name="kb_source_status",
                native_enum=False,
                length=32,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column(
            "config_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("extracted_text", sa.Text(), nullable=True),
        sa.Column("byte_size", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["kb_id"],
            ["knowledge_base.id"],
            name=op.f("fk_kb_source_kb_id_knowledge_base"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_kb_source_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kb_source")),
    )
    op.create_index(op.f("ix_kb_source_kb_id"), "kb_source", ["kb_id"], unique=False)
    op.create_index(op.f("ix_kb_source_status"), "kb_source", ["status"], unique=False)
    op.create_index(op.f("ix_kb_source_tenant_id"), "kb_source", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_kb_source_tenant_id"), table_name="kb_source")
    op.drop_index(op.f("ix_kb_source_status"), table_name="kb_source")
    op.drop_index(op.f("ix_kb_source_kb_id"), table_name="kb_source")
    op.drop_table("kb_source")
    op.drop_index(op.f("ix_agent_kb_link_kb_id"), table_name="agent_kb_link")
    op.drop_index(op.f("ix_agent_kb_link_agent_id"), table_name="agent_kb_link")
    op.drop_table("agent_kb_link")
    op.drop_index(op.f("ix_knowledge_base_tenant_id"), table_name="knowledge_base")
    op.drop_table("knowledge_base")
    # ### end Alembic commands ###
