"""api keys and channels

Revision ID: 0007
Revises: 0006
Create Date: 2026-08-29 16:25:51.469114
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_key",
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("prefix", sa.String(length=24), nullable=False),
        sa.Column("scopes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rate_limit_per_minute", sa.Integer(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"], ["agent.id"], name=op.f("fk_api_key_agent_id_agent"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_api_key_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_key")),
    )
    op.create_index(op.f("ix_api_key_agent_id"), "api_key", ["agent_id"], unique=False)
    op.create_index(op.f("ix_api_key_key_hash"), "api_key", ["key_hash"], unique=True)
    op.create_index(op.f("ix_api_key_tenant_id"), "api_key", ["tenant_id"], unique=False)
    op.create_table(
        "channel_config",
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column(
            "channel_type",
            sa.Enum("web", "whatsapp", name="channel_type", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("active", "disabled", name="channel_status", native_enum=False, length=32),
            server_default="active",
            nullable=False,
        ),
        sa.Column(
            "credentials_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "settings_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agent.id"],
            name=op.f("fk_channel_config_agent_id_agent"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_channel_config_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_channel_config")),
        sa.UniqueConstraint(
            "agent_id", "channel_type", name="uq_channel_config_agent_id_channel_type"
        ),
    )
    op.create_index(
        op.f("ix_channel_config_agent_id"), "channel_config", ["agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_channel_config_tenant_id"), "channel_config", ["tenant_id"], unique=False
    )
    op.create_table(
        "webhook_endpoint",
        sa.Column("agent_id", sa.Uuid(), nullable=True),
        sa.Column("url", sa.String(length=2000), nullable=False),
        sa.Column("secret", sa.String(length=128), nullable=False),
        sa.Column("events", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "disabled", name="webhook_status", native_enum=False, length=32),
            server_default="active",
            nullable=False,
        ),
        sa.Column("failure_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_delivery_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agent.id"],
            name=op.f("fk_webhook_endpoint_agent_id_agent"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_webhook_endpoint_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_endpoint")),
    )
    op.create_index(
        op.f("ix_webhook_endpoint_agent_id"), "webhook_endpoint", ["agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_webhook_endpoint_tenant_id"), "webhook_endpoint", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_webhook_endpoint_tenant_id"), table_name="webhook_endpoint")
    op.drop_index(op.f("ix_webhook_endpoint_agent_id"), table_name="webhook_endpoint")
    op.drop_table("webhook_endpoint")
    op.drop_index(op.f("ix_channel_config_tenant_id"), table_name="channel_config")
    op.drop_index(op.f("ix_channel_config_agent_id"), table_name="channel_config")
    op.drop_table("channel_config")
    op.drop_index(op.f("ix_api_key_tenant_id"), table_name="api_key")
    op.drop_index(op.f("ix_api_key_key_hash"), table_name="api_key")
    op.drop_index(op.f("ix_api_key_agent_id"), table_name="api_key")
    op.drop_table("api_key")
    # ### end Alembic commands ###
