"""source sync scheduling

Revision ID: 0008
Revises: 0007
Create Date: 2026-08-29 18:18:34.156475
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0008"
down_revision: str | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "kb_source",
        sa.Column("sync_interval_minutes", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column("kb_source", sa.Column("next_sync_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "kb_source",
        sa.Column("consecutive_failures", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column("kb_source", sa.Column("sync_cursor", sa.String(length=500), nullable=True))
    op.create_index(op.f("ix_kb_source_next_sync_at"), "kb_source", ["next_sync_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_kb_source_next_sync_at"), table_name="kb_source")
    op.drop_column("kb_source", "sync_cursor")
    op.drop_column("kb_source", "consecutive_failures")
    op.drop_column("kb_source", "next_sync_at")
    op.drop_column("kb_source", "sync_interval_minutes")
    # ### end Alembic commands ###
