"""whatsapp channel

Revision ID: 0009
Revises: 0008
Create Date: 2026-08-29 19:57:29.590033
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0009"
down_revision: str | None = "0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "whatsapp_message",
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=True),
        sa.Column(
            "direction",
            sa.Enum(
                "inbound",
                "outbound",
                name="whatsapp_message_direction",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("provider_message_id", sa.String(length=255), nullable=True),
        sa.Column("wa_contact_id", sa.String(length=64), nullable=False),
        sa.Column(
            "message_type",
            sa.Enum(
                "text",
                "image",
                "document",
                "audio",
                "video",
                "template",
                "unsupported",
                name="whatsapp_message_type",
                native_enum=False,
                length=32,
            ),
            server_default="text",
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "received",
                "processed",
                "sent",
                "delivered",
                "read",
                "failed",
                name="whatsapp_delivery_status",
                native_enum=False,
                length=32,
            ),
            server_default="queued",
            nullable=False,
        ),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("template_name", sa.String(length=255), nullable=True),
        sa.Column("error_detail", sa.String(length=500), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "meta_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agent.id"],
            name=op.f("fk_whatsapp_message_agent_id_agent"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["channel_config.id"],
            name=op.f("fk_whatsapp_message_connection_id_channel_config"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversation.id"],
            name=op.f("fk_whatsapp_message_conversation_id_conversation"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_whatsapp_message_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_whatsapp_message")),
        sa.UniqueConstraint(
            "connection_id",
            "provider_message_id",
            name="uq_whatsapp_message_connection_id_provider_message_id",
        ),
    )
    op.create_index(
        op.f("ix_whatsapp_message_agent_id"), "whatsapp_message", ["agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_whatsapp_message_connection_id"),
        "whatsapp_message",
        ["connection_id"],
        unique=False,
    )
    op.create_index(
        "ix_whatsapp_message_contact",
        "whatsapp_message",
        ["connection_id", "wa_contact_id", "direction", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_whatsapp_message_conversation_id"),
        "whatsapp_message",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_whatsapp_message_tenant_id"), "whatsapp_message", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_whatsapp_message_tenant_id"), table_name="whatsapp_message")
    op.drop_index(op.f("ix_whatsapp_message_conversation_id"), table_name="whatsapp_message")
    op.drop_index("ix_whatsapp_message_contact", table_name="whatsapp_message")
    op.drop_index(op.f("ix_whatsapp_message_connection_id"), table_name="whatsapp_message")
    op.drop_index(op.f("ix_whatsapp_message_agent_id"), table_name="whatsapp_message")
    op.drop_table("whatsapp_message")
    # ### end Alembic commands ###
