"""agent tools

Revision ID: 0010
Revises: 0009
Create Date: 2026-08-29 21:57:16.828921
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0010"
down_revision: str | None = "0009"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_tool",
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("endpoint_url", sa.String(length=2000), nullable=False),
        sa.Column(
            "http_method",
            sa.Enum(
                "get", "post", "put", "patch", name="tool_http_method", native_enum=False, length=32
            ),
            server_default="get",
            nullable=False,
        ),
        sa.Column(
            "auth_type",
            sa.Enum(
                "none",
                "api_key_header",
                "bearer",
                "basic",
                name="tool_auth_type",
                native_enum=False,
                length=32,
            ),
            server_default="none",
            nullable=False,
        ),
        sa.Column(
            "auth_config_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "request_schema_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "response_mapping_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("enabled", "disabled", name="tool_status", native_enum=False, length=32),
            server_default="enabled",
            nullable=False,
        ),
        sa.Column("timeout_seconds", sa.Float(), nullable=True),
        sa.Column("cache_ttl_seconds", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_called_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agent.id"],
            name=op.f("fk_agent_tool_agent_id_agent"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_agent_tool_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_tool")),
        sa.UniqueConstraint("agent_id", "name", name="uq_agent_tool_agent_id_name"),
    )
    op.create_index(op.f("ix_agent_tool_agent_id"), "agent_tool", ["agent_id"], unique=False)
    op.create_index(op.f("ix_agent_tool_tenant_id"), "agent_tool", ["tenant_id"], unique=False)
    op.create_table(
        "tool_policy",
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column(
            "allowed_hosts",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("max_calls_per_turn", sa.Integer(), server_default="3", nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agent.id"],
            name=op.f("fk_tool_policy_agent_id_agent"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_tool_policy_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_policy")),
        sa.UniqueConstraint("agent_id", name="uq_tool_policy_agent_id"),
    )
    op.create_index(op.f("ix_tool_policy_agent_id"), "tool_policy", ["agent_id"], unique=False)
    op.create_index(op.f("ix_tool_policy_tenant_id"), "tool_policy", ["tenant_id"], unique=False)
    op.create_table(
        "tool_call",
        sa.Column("tool_id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=True),
        sa.Column(
            "outcome",
            sa.Enum(
                "succeeded",
                "cached",
                "failed",
                "timed_out",
                "refused",
                name="tool_outcome",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "arguments_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), server_default="0", nullable=False),
        sa.Column("result_text", sa.Text(), nullable=True),
        sa.Column("error_detail", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversation.id"],
            name=op.f("fk_tool_call_conversation_id_conversation"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tool_id"],
            ["agent_tool.id"],
            name=op.f("fk_tool_call_tool_id_agent_tool"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_call")),
    )
    op.create_index(
        op.f("ix_tool_call_conversation_id"), "tool_call", ["conversation_id"], unique=False
    )
    op.create_index(op.f("ix_tool_call_tool_id"), "tool_call", ["tool_id"], unique=False)
    op.create_index(
        "ix_tool_call_tool_id_created_at", "tool_call", ["tool_id", "created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tool_call_tool_id_created_at", table_name="tool_call")
    op.drop_index(op.f("ix_tool_call_tool_id"), table_name="tool_call")
    op.drop_index(op.f("ix_tool_call_conversation_id"), table_name="tool_call")
    op.drop_table("tool_call")
    op.drop_index(op.f("ix_tool_policy_tenant_id"), table_name="tool_policy")
    op.drop_index(op.f("ix_tool_policy_agent_id"), table_name="tool_policy")
    op.drop_table("tool_policy")
    op.drop_index(op.f("ix_agent_tool_tenant_id"), table_name="agent_tool")
    op.drop_index(op.f("ix_agent_tool_agent_id"), table_name="agent_tool")
    op.drop_table("agent_tool")
    # ### end Alembic commands ###
